SETLIST_API_KEY = "setlist_api_key_goes_here"
SPOTIFY_API_KEY = "spotify_api_key_goes_here"
ECHONEST_API_KEY = "echonest_api_key_goes_here"
ECHONEST_CONSUMER_KEY = "echonest_consumer_key_goes_here"
ECHONEST_SHARED_SECRET = "echonest_shared_secret_goes_here"
